### ISSUE TITLE
编译完uboot之后，从开发板启动不起来,没有一点打印的数据

### ISSUE THREAD

**Issue by YUGEEV5** [jason416/uboot-2017-11#5]
![image](https://user-images.githubusercontent.com/53249578/105623865-1ce78500-5e58-11eb-9ce5-933ce36c53be.png)
刚上电的时候，能打印个黑色的块块。咋回事啊

**Comment by jason416** [comment]
@YUGEEV5 你查下，看是不是线没接对，还有波特率不匹配，板子的波特率默认115200的。

**Comment by YUGEEV5** [comment]
@jason416 我又重新插拔了一下，能显示字符了，但是现在，很操蛋的事情出现了，就是在这个串口终端我输不进去字符，而且还很卡，就是你按个回车，过几秒给你反应。字符根本就输不进去，但是按回车，我看他貌似能接受，咋回事啊，大佬

**Comment by jason416** [comment]
> @jason416 我又重新插拔了一下，能显示字符了，但是现在，很操蛋的事情出现了，就是在这个串口终端我输不进去字符，而且还很卡，就是你按个回车，过几秒给你反应。字符根本就输不进去，但是按回车，我看他貌似能接受，咋回事啊，大佬

你看下，是不是硬件接线没有对啊。你物理接线怎么操作的啊，那个板子自带的COM口是232电平的，不能直接拿CH340的引脚接上去。

**Comment by YUGEEV5** [comment]
![image](https://user-images.githubusercontent.com/53249578/105633832-e7618c80-5e95-11eb-9e8e-ebeb3fa74c70.png)
@jason416 这个是我的接线方法，我转了。

**Comment by YUGEEV5** [comment]
@jason416 我现在也不知道是啥原因，要不大佬，你把你的那个bin文件发给我我试试，我是直接执行你的那个脚本编译的啊，不应该出错啊，是不是我的这线太辣鸡了，但是跑下面这个Uboot,还是很丝滑的，但是他下面这个我看这版本也好老的了，也不支持网络。
![image](https://user-images.githubusercontent.com/53249578/105633970-969e6380-5e96-11eb-8e2f-e490c81613b0.png)

**Comment by jason416** [comment]
@YUGEEV5 你直接下这个仓库的release版本，用v0.4，可以直接用。

**Comment by YUGEEV5** [comment]
@jason416 好的，我试下。

**Comment by YUGEEV5** [comment]
@jason416 这个V0.4版本的，我编译下载进去，这次是直接都不能操作了，
![image](https://user-images.githubusercontent.com/53249578/105634512-4e347500-5e99-11eb-8416-9f5f3e1ab311.png)

**Comment by jason416** [comment]
@YUGEEV5 你烧些的版本不对呢，还是你自己编译的固件时间。你重新弄下你的TF卡呢。

**Comment by YUGEEV5** [comment]
> @YUGEEV5 你烧些的版本不对呢，还是你自己编译的固件时间。你重新弄下你的TF卡呢。

大佬，我上次搞了好久还是没弄好，我以为是我的线坏了，现在我用我同学的板子和线，也试了，还是可卡，感觉串口的数据被堵住了，过个1 到2 s，才把数据发过来，中间还断断续续的，还有你上次说的那个v0.4,版本的里面没有u-boot-iTOP-4412.bin
这个文件，我自己重新编译了一下。是下面这个仓库的地址吗？
![图片](https://user-images.githubusercontent.com/53249578/115949658-20e37b80-a509-11eb-8b15-935073ea37f1.png)

**Comment by jason416** [comment]
@YUGEEV5 对的，就是哪个地址，你试一下呢。

**Comment by YUGEEV5** [comment]
> @YUGEEV5 对的，就是哪个地址，你试一下呢。

还是那个问题，我烧录了官方的uboot，还是那。https://www.bilibili.com/video/BV1pf4y1s73N ，你可以看看我这个问题。

**Comment by jason416** [comment]
> > @YUGEEV5 对的，就是哪个地址，你试一下呢。
> 
> 还是那个问题，我烧录了官方的uboot，还是那。https://www.bilibili.com/video/BV1pf4y1s73N ，你可以看看我这个问题。

你换个串口终端试一下呢？比如像putty这种；还有就是换下USB转串口的模块。如果都不能解决的话，可以怀疑是不是硬件有问题，可以找讯为售后，把板子寄过去，让他们看看。

**Comment by YUGEEV5** [comment]
> > > @YUGEEV5 对的，就是哪个地址，你试一下呢。
> > 
> > 
> > 还是那个问题，我烧录了官方的uboot，还是那。https://www.bilibili.com/video/BV1pf4y1s73N ，你可以看看我这个问题。
> 
> 你换个串口终端试一下呢？比如像putty这种；还有就是换下USB转串口的模块。如果都不能解决的话，可以怀疑是不是硬件有问题，可以找讯为售后，把板子寄过去，让他们看看。

putty我试了，也是这，他们以前的uboot，我就不卡，可以用，但是他们以前的那个不支持设备树，我的那个U转串是CH340，你的那个是啥啊？

**Comment by jason416** [comment]
@YUGEEV5 我用的讯为官方的那个，好像不是CH340，是PL2xx的。他那个COM口是RS232电平，常用的U转串口是TTL电平；你看下是不是硬件没用对？

**Comment by YUGEEV5** [comment]
@jason416  好的，我再买一根PL2303接口的吧，再试试。

**Comment by YUGEEV5** [comment]
@jason416  新买的线到了，已经不卡了，果然是CH340芯片的问题，辣鸡CH340，果然便宜的没好货。。

**Comment by YUGEEV5** [comment]
@jason416 
```c
U-Boot 2017.11 (Apr 27 2021 - 14:51:08 +0800) for itop-4412

CPU:   Exynos4412 @ 1 GHz
Model: itop-4412 based on Exynos4412
Board: itop-4412 based on Exynos4412
DRAM:  1 GiB
WARNING: Caches not enabled
MMC:   SAMSUNG SDHCI: 0, EXYNOS DWMMC: 1
sdhci_transfer_data: Error detected in status(0x208002)!
sdhci_transfer_data: Error detected in status(0x208002)!
sdhci_transfer_data: Error detected in status(0x208000)!
*** Warning - read failed, using default environment

Net:   No ethernet found.
Hit any key to stop autoboot:  0

```
我这个加载之后，出现了这个错误，不能使用saveenv 这个保存命令，直接保存失败，保存如下所示：
```c
u-boot # saveenv
Saving Environment to MMC...
Writing to MMC(0)... failed

```

**Comment by jason416** [comment]
@YUGEEV5 可能是硬件参数不匹配之类的，可以用了就行。
下面的消息好像有错误，你用的什么的TF卡呢？推荐用闪迪或者三星的。

**Comment by YUGEEV5** [comment]
@jason416 这个内存卡，是在我家从老的手机上去取下来的，估计是内存卡的问题，我换个内存卡试试

**Comment by jason416** [comment]
> @jason416 这个内存卡，是在我家从老的手机上去取下来的，估计是内存卡的问题，我换个内存卡试试

有任何进展吗？问题解决了吗

**Comment by YUGEEV5** [comment]
> > @jason416 这个内存卡，是在我家从老的手机上去取下来的，估计是内存卡的问题，我换个内存卡试试
> 
> 有任何进展吗？问题解决了吗

我在网上找到这个帖子;https://blog.csdn.net/u013779722/article/details/60311216 ,注释掉了这两行,烧写到SD卡,就可以了,感谢大佬关心.

**Comment by jason416** [comment]
> > > @jason416 这个内存卡，是在我家从老的手机上去取下来的，估计是内存卡的问题，我换个内存卡试试
> > 
> > 
> > 有任何进展吗？问题解决了吗
> 
> 我在网上找到这个帖子;https://blog.csdn.net/u013779722/article/details/60311216 ,注释掉了这两行,烧写到SD卡,就可以了,感谢大佬关心.

OK，相互学习！我现在把这个issue关了。
